FROM php:8.3-cli-trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN set -eux; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends \
    jq \
    mariadb-client \
    nano \
    rsync \
    zip \
    zstd; \
    curl -sSLf -o /usr/local/bin/install-php-extensions \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions; \
    chmod +x /usr/local/bin/install-php-extensions; \
    install-php-extensions \
    exif \
    gd \
    igbinary \
    imagick \
    intl \
    memcached \
    mysqli \
    pcntl \
    pdo_mysql \
    pdo_pgsql \
    redis \
    soap \
    zip \
    zstd; \
    rm /usr/local/bin/install-php-extensions; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

COPY ./conf/php-cli.ini /usr/local/etc/php/conf.d/01-php.ini

USER www-data

WORKDIR /app

# List of supported extensions available here:
# https://github.com/mlocati/docker-php-extension-installer#readme
