name: Build & Push Images

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile.*"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/php_ext

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # - dockerfile: Dockerfile.7.1-fpm
          #   version: "7.1"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.7.2-fpm
          #   version: "7.2"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.7.3-fpm
          #   version: "7.3"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.7.4-cli.builder
          #   version: "7.4"
          #   flavor: "cli-builder"
          # - dockerfile: Dockerfile.7.4-fpm
          #   version: "7.4"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.8.0-fpm
          #   version: "8.0"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.8.1-fpm
          #   version: "8.1"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.8.2-fpm
          #   version: "8.2"
          #   flavor: "fpm"
          # - dockerfile: Dockerfile.8.3-cli.builder
          #   version: "8.3"
          #   flavor: "cli-builder"
          - dockerfile: Dockerfile.8.3-fpm
            version: "8.3"
            flavor: "fpm"
          # - dockerfile: Dockerfile.8.4-cli.builder
          #   version: "8.4"
          #   flavor: "cli-builder"
          - dockerfile: Dockerfile.8.4-fpm
            version: "8.4"
            flavor: "fpm"

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Validate build configuration
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ${{ matrix.dockerfile }}
      #     platforms: linux/amd64,linux/arm64
      #     call: check

      # - name: Extract metadata
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: ${{ env.IMAGE_REPO }}
      #     tags: |
      #       type=raw,value=${{ matrix.version }}-${{ matrix.flavor }}

      - name: Build & push ${{ matrix.version }}-${{ matrix.flavor }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          # sbom: true
          push: true
          # provenance: mode=max
          tags: |
            ${{ env.IMAGE_REPO }}:${{ matrix.version }}-${{ matrix.flavor }}
